# -*- coding: utf-8 -*-
"""day05_fstrings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iQg-8GtP6KfmErWH6LdMVEY59oeLqs9
"""

#f-strings
Goal="Python Developer"
year=2026
print(f"My Goal is to become {Goal} in {year}")

a=10
b=11
res=a+b
print(f"The sum of {a} and {b} is : {res}")