# -*- coding: utf-8 -*-
"""day03_math

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jG4c3IIV_33wwUTktLzizwQz8aM8eVJG
"""

#Operators
year_of_birth=int(input("Enter bith year:"))
present_year=int(input("Enter present year:"))
present_age=present_year-year_of_birth
print(present_age)