# -*- coding: utf-8 -*-
"""day02_variables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biws5zVMcMaYLeZLvOLOOOu9qkJ-EdQF
"""

name="Rithwik"  #string
age=23  #int
print(name)  #variable means a storage box inside the computer which means it stores the data
print(age)