# -*- coding: utf-8 -*-
"""day01_printing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4oWofZTyZlCYhIcBDjpn7i15Zq3rTa9
"""

print("Hello,World")
print("Iam Learning Python")  #print is a built-in function which displays the data what we enter inside the paranthesis