# -*- coding: utf-8 -*-
"""day06_string_methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSEGvcW25i3oGvsPtFDllMhtHHd-MnyN
"""

#Transforming Text
Name="rithwik"
print(f"My Name is {Name.upper()}")   #converting small letters to capital letters
print(len(Name))  #printing the length of the name