# -*- coding: utf-8 -*-
"""day08_booleans

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qv9XMi_PVNDqTyvVNDgJf78f_YcIYaxY
"""

hours_studied=float(input("Enter number of hours:"))
target_hours=float(input("Enter target hours:"))
print(hours_studied>=target_hours)
print(type(hours_studied>=target_hours))