# -*- coding: utf-8 -*-
"""day09_if_else

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMs3ivUmasrZXqXWRn13PD13PSjjPDRS
"""

attendance=int(input("Enter attendance:"))
if attendance>=75:
  print("Allowed for the exam")
else:
  print("Not allowed")