# -*- coding: utf-8 -*-
"""day04_datatypes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRGUn_6UBve2vBtdFrhrpNVMX6vCfwLy
"""

#Datatypes
Name="Rithwik"
Age=22
Grade=7.6
print(type(Name))
print(type(Age))
print(type(Grade))