# -*- coding: utf-8 -*-
"""day11_logical_operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1BnKfAx1zENqVmz_nrUp9YIUebw7Qwk
"""

age=int(input("Enter age:"))
student=input("Enter yes/no:")
if age<6 or age>67:
  print("Ticket cost is 0")
elif student in ["yes","Yes","YES"] and age<25:
  print("Ticket cost is 0")
else:
  print("Ticket is 40")

salary=int(input("Enter salary:"))
has_defaulted=input("Enter yes/no:")
if salary>=500000 and has_defaulted in ["No","no","NO"]:
  print("Mortgage Approved: Proceed to Underwriting")
else:
  print("Mortgage Denied: High Financial Risk")