# -*- coding: utf-8 -*-
"""day10_multi_conditions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzjXNClu96TtBlprLa3bicLZrZmr76b_
"""

temp=float(input("Enter the temperature:"))
if temp<0.0:
  print("Sub-Zero freezing")
elif temp>=0.0 and temp<=15.0:
  print("Cool Alpine Costal")
elif temp>15.0:
  print("Anomalous Warm Zone")

bp=int(input("Enter battery percentage:"))
ph=input("Enter peak hours:")
if bp<20:
  print("Priority Charging Status: Maximum Grid Allocation Authorized")
elif bp>=20 and bp<=80:
  if ph=="yes":
    print("Standard Grid Load: Peak Tariff Rates Applied")
  else:
    print("Balanced Grid Load: Eco Discount Rate Applied")
else:
  print("Battery Preservation State: Trickle Charge Mode Engaged")