# -*- coding: utf-8 -*-
"""day15_list_indexing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2MU9edbQG5Gvl6iY-ehuXxPKjwT6XMG
"""

#Lists
prices=[150, 320, 400, 710]
prices[3]=950
print(prices)

logs=[102, 304, 508, 701, 999]
a=logs[0]
b=logs[-1]
print(f"Difference is:{b-a}")