# -*- coding: utf-8 -*-
"""day14_lists_and_loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BK-lRlL5uka-eyzK1LW5AY1FcUJeB9B_
"""

temp=[12,15,18,14,16]
for i in temp:
  print(f"Adjusted Temperatures are: {i+2}")

transactions=[100,250,50,400]
total_balance=0
for i in transactions:
  total_balance=total_balance+i
print(f"Total Balance is: {total_balance}")