# -*- coding: utf-8 -*-
"""day12_while_loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QObwiPYlxoGJVdW6umGk6iNATXlW79u
"""

attempts=1
while attempts<=5:
  print(f"Connecting to BankID API... Attempt {attempts}")
  attempts=attempts+1
print("Connection Timeout: Server Unreachable")

pin=int(input("enter the pin:"))
while pin!=1234:
  print("Wrong PIN Try again")
  pin=int(input("enter the pin:"))
print("Access Granted")