# -*- coding: utf-8 -*-
"""day13_for_loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My31Otml5vj2bCSF1RdTH_RHV82HBo-P
"""

#for loop
for x in range(5,0,-1):
  print(f"System launch in {x} Seconds")
print("Launch Successful")

for x in range(2,11,2):
  print(f"Testing Sensor Number: {x}")
print("All Are Verified")