# -*- coding: utf-8 -*-
"""day19_filtering_loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ae_mDfYWW7jClwJPvIyVsEnCPqxoRXsH
"""

balances=[2500,-120,4300,-50,800,0]
for i in balances:
  if i<0:
    print(f"Critical Alert: Overdraft Account Detected: {i}")

scores=[45, 82, 71, 30, 95, 50]
pass_count=0
for i in scores:
  if i>=50:
    print(f"Passing Score: {i}")
    pass_count=pass_count+1
print(f"Total Passing Students: {pass_count}")