# -*- coding: utf-8 -*-
"""day16_list_methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Spf6D6S1YHP5RoPqz0otJ4ykKdoe1tKW
"""

queue=[]
queue.append(1001)
queue.append(1002)
queue.append(1003)
queue.pop(0)
print(queue)

dataset=[45, 89, 12, 34, 999]
dataset.pop()
dataset.append(56)
print(dataset)