# -*- coding: utf-8 -*-
"""day17_list_length

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WalfyRMfCN7pDVNrGPAJV1tFIs4aJ2CW
"""

inv=[50, 100, 150, 200, 250, 300]
for i in range(len(inv)):
  print(f"Processing Position {i} Value: {inv[i]}")

orders=[701, 802, 903, 404, 505]
length=len(orders)-1
item=orders[length]
print(item)