# -*- coding: utf-8 -*-
"""day18_min_max

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I6E4Ogb4q0j2Yow4hG_7UC74Az4ssE1a
"""

readings=[140, 620, 890, 430, 210]
max_val=readings[0]
for i in readings:
  if i>max_val:
    max_val=i
print(f"Peak Amplitude Detected: {max_val}")

depths=[45, 12, 88, 5, 31]
min_val=depths[0]
for i in depths:
  if i<min_val:
    min_val=i
print(f"Minimum Depth Target: {min_val}")