# -*- coding: utf-8 -*-
"""day22_negative_indexing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIZXYumWLNy_BxfZeDcxyacDb6gkuasQ
"""

n=[1,2,3,4,5]
print(n[-5:-2])

db_latencies=[12.4, 15.1, 9.8, 11.2, 14.5]
print(db_latencies[-1])

audit_trail=[500, 1200, -350, 450]
audit_trail[-2]=900
print(audit_trail)