# -*- coding: utf-8 -*-
"""day21_list_slicing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9TTr-JmHO_bpk5Z7srVuvb4xxiz5sZ0
"""

temp=[12,15,18,21,24,27]
mid_day=temp[2:5]
print(mid_day)

stock_prices=[105,110,115,120,125]
base_lines=stock_prices[:3]
print(base_lines)