# -*- coding: utf-8 -*-
"""day24_matrix_filtering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPTXHNiAMQbjazOmW8NXt6vQm8wvAFOp
"""

transaction_grid = [
       [1200, 4500, 800],
       [9000, 150,  3200],
       [60,   11000, 450]
   ]
l=[]
for i in transaction_grid:
  for j in i:
    if j>4000:
      l.append(j)
print(l)

packet_matrix = [
[0,  -1,  4],
[-1, -1,  0],
[12,  0, -1]
]
count=0
for i in packet_matrix:
  for j in i:
    if j==-1:
      count=count+1
print(count)