# -*- coding: utf-8 -*-
"""day23_matrix_traversal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeK0lNAhuZ8a3fDiFpIsOMl2mKBMN15x
"""

grid_data = [
    [101, 102, 103],
    [201, 202, 203],
    [301, 302, 303]
]
for i in grid_data:
  for j in i:
    print(j)

incident_logs = [
[14, 22, 8],
[0,  5,  19],
[31, 12, 4]
]
total=0
for i in incident_logs:
  for j in i:
    total=total+j
print(total)