# -*- coding: utf-8 -*-
"""day22_negative_slicing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrepEomQ9kKt56Imn_IkDnjKFGn8aAMW
"""

trade_volumes = [4400, 12000, 8900, 15500, 23000, 11000, 17500]
risk_window = trade_volumes[-4:-1]
print(risk_window)

sensor_streams = [0.12, 0.85, 0.94, 0.33, 0.45, 0.71, 0.58]
tail_telemetry= sensor_streams[-4:]
print(tail_telemetry)