# -*- coding: utf-8 -*-
"""day21_advanced_slicing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgB6sBtNp9URKlBT7UQFYswdnF6r6WxK
"""

numbers=[110,245,380,515,650,785,920]
print(numbers[1:6:2])

numbers=[5001,5002,5003,5004,5005]
print(numbers[::-1])

numbers=[5001,5002,5003,5004,5005]
empty=[]
for i in range(len(numbers)-1,-1,-1):
  empty.append(numbers[i])
print(empty)