# -*- coding: utf-8 -*-
"""day23_2d_lists

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQ-W_jHbuYgBjEChbMsJIXKSErTqCUZu
"""

a=[
    [45,62,120],
    [88,79,340],
    [23,41,95]
]
b=a[1][1]
print(b)

l=[
    [1200,1350,1400],
    [450,480,510],
    [700,690,610]
]
l[2][2]=850
r=l
print(r)