# -*- coding: utf-8 -*-
"""project1_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKVXXAs2pKGR8wrU65ku5gEuJGyYPk25
"""

numbers=[101,102,103]
choice=""
while choice!="3":
  choice=input("Enter choice:")
  if choice=="1":
    print(numbers)
  elif choice=="2":
    new_num=int(input("Enter new number:"))
    numbers.append(new_num)
  elif choice=="3":
    print("Good Bye")
  else:
    print("Error")
print(numbers)