# -*- coding: utf-8 -*-
"""weekly_assignment_days_15_20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaCpLCqQ1Ef9vw-IO9-S73gPs2p0wGxn
"""

prices=[150,320,400,710]
prices[2]=950
print(prices)

queue=[10,20,30]
queue.append(40)
queue.pop(0)
print(queue)

metrics=[85,92,78]
length=len(metrics)
for i in range(length):
  print(f"Index {i}- value : {metrics[i]}")
print(f"Total Length is : {length}")