# -*- coding: utf-8 -*-
"""week01_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebNCrFVx7Mx6BkVs2gJhJRtb1vHmnWtw
"""

Name=input("Enter a Name:")
Birth_Year=int(input("Enter Birth_Year:"))
Weekly_Study_Goal=float(input("Enter Weekly_Study_Goal:"))
print(f"Name:{Name}")
print(f"Birth_Year:{Birth_Year}")
print(f"Weekly_Study_Goal:{Weekly_Study_Goal/7} Hours Per Day")
print(type(Name))
print(type(Birth_Year))
print(type(Weekly_Study_Goal))